############# English Navigation ##############

# Main Menu
[[main]]
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  name = "Projects"
  url = "/projects/"
  weight = 2

[[main]]
  name = "Services"
  url = "/services/"
  weight = 3

[[main]]
  name = "About"
  url = "/about/"
  weight = 4

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 5

[[main]]
  parent = "Services"
  name = "Architecture"
  url = "/architecture"
  weight = 6

[[main]]
parent = "Services"
name = "Architecture"
url = "/architecture"
weight = 7

[[main]]
parent = "Services"
name = "Planning"
url = "/planning"
weight = 8

[[main]]
parent = "Services"
name = "Interior Design"
url = "/design"
weight = 9

[[main]]
parent = "Services"
name = "Project Management"
url = "/management"
weight = 10

#[[main]]
#name = "404 Page"
#url = "/404"
#weight = 10

# Footer Menu
[[footer]]
  name = "About"
  url = "/about"
  weight = 1

[[footer]]
  name = "Projects"
  url = "/projects"
  weight = 2

[[footer]]
  name = "Privacy Policy"
  url = "/privacy-policy"
  weight = 3
