name = "StudioFacet"
description = "StudioFacet"
version = 0.134.3

tags = [
  "blog",
  "responsive",
  "minimal",
  "personal",
  "light",
  "dark",
  "multilingual",
  "landing",
  "contact",
  "dark mode",
  "tailwindcss",
]

features = [
  "Multi-Authors",
  "Search",
  "Multilingual",
  "Dark Mode",
  "Taxonomies",
]

[author]
name = "StudioFacet"
homepage = "https://zeon.studio"

[original]
author = "Studio Facet"
homepage = "https://zeon.studio"
repo = "https://github.com/zeon-studio/themeplate" 

